# Site settings
title: Arctic Fox
email: 
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
baseurl: "/arctic-fox-theme" # the subpath of your site, e.g. /blog/
url: "http://ixqifeba.github.io" # the base hostname & protocol for your site
twitter_username: username
github_username: username
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  galleries:
    output: true
    permalink: "/galleries/:path/"
  posts:
    output: true
  projects:
    output: true
    permalink: "/projects/:path/"
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
plugins:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
