<!DOCTYPE html>
<html>

  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Arctic Fox</title>
  <meta name="description" content="Jekyll Theme Demo
">

  <link rel="stylesheet" href="/arctic-fox-theme/css/main.css">
  <link rel="canonical" href="http://ixqifeba.github.io/arctic-fox-theme/config-forestryio.yml">
  <link rel="alternate" type="application/rss+xml" title="Arctic Fox" href="http://ixqifeba.github.io/arctic-fox-theme/feed.xml" />

  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,700' rel='stylesheet' type='text/css'>
</head>


  <body>

    <div class="site-header">

    <nav class="site-nav">
      <a href="#" class="menu-icon">
        <i class="fa fa-navicon fa-lg"></i>
      </a>

      <div class="trigger">
          <a class="page-link" href="/arctic-fox-theme/">Home</a>
        
          
          <a class="page-link" href="/arctic-fox-theme/about/">About</a>
          
        
          
        
          
        
          
        
          
        
        
          <a class="page-link" href="/arctic-fox-theme/galleries/comicz/">Comics</a>
        
          <a class="page-link" href="/arctic-fox-theme/galleries/drawings/">Drawings</a>
        
      </div>
    </nav>


</div>


    <div class="page-content">
      <div class="wrapper">
        <div class="post">

  <header class="post-header">
    <h1 class="post-title"></h1>
  </header>

  <article class="post-content">
    ---
title: Arctic Fox
email: 
description: 'Jekyll Theme Demo

'
baseurl: "/arctic-fox-theme"
url: http://ixqifeba.github.io
twitter_username: username
github_username: username
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: galleries
  values:
    layout: galleries
collections:
  galleries:
    output: true
    permalink: "/galleries/:path/"
  posts:
    output: true
  projects:
    output: true
    permalink: "/projects/:path/"
jekyll-archives:
  enabled: all
  layout: archive
plugins:
- jekyll-menus
- jekyll-feed
- jekyll-archives
timezone: America/Los_Angeles

  </article>

</div>
      </div>
    </div>

    <div class="footer center">

</div>


  </body>
</html>
